### ISSUE TITLE
Countdown sound Inconsistent behaviour

### ISSUE THREAD

**Issue by Guntistik** [Raphire/SusAlert#7] opened 2022-10-16 05:48 UTC
it's perfect besides the fact it sometimes just restarts mid kill or randomly and then you are just left for dead. Also the beeping also only works like every so often, its either 3 lil beeps, 1 beep when hit comes, or none at all.

**Comment by Raphire** [comment] 2022-10-16 21:39
Heya, SusAlert restarting during a kill has already been reported in issue #6, and this has been addressed in the latest update.

As for the countdown sounds (beeps) not working correctly, can you elaborate? Does it sometimes not play any sounds at all, or does it skip some of the beeps, and does this consistently do this for every attack or just every now and again? It should do 1 beep every second (3 times) while counting down for the attack and then the quick beeps as the attack comes in (assuming you use the default sound setting).

Thanks!

**Comment by Raphire** [comment] 2023-01-25 15:59
Cannot reproduce issue related to sound. Try refreshing or reopening SusAlert if it happens again in the future, it may be an issue related to caching.

**Comment by Raphire** [comment] 2023-01-25 16:00
Cannot reproduce issue related to sound. Try refreshing (F5) or reopening SusAlert if it happens again in the future, it may be an issue related to caching.

**Closed as not planned by Raphire** 2023-01-25 16:00 UTC
Labels: bug
